/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, {Component} from 'react';
import {StyleSheet, Text, View, Button} from 'react-native';
import FawrySdk from 'react-native-fawry-sdk';
import secrets from './secrets';

export default class App extends Component<{}> {
  componentDidMount() {
    FawrySdk.initSDK(FawrySdk.STYLES.STYLE1);
  }

  initPaymentPlugin = () => {
    const data = {
      merchantID: secrets.merchantID,
      serverURL: secrets.serverURL,
      items: [
        {
          price: '100',
          description: 'Hello',
          quantity: '1',
          sku: '1234',
        },
      ],
      language: FawrySdk.LANGUAGES.EN,
    };
    FawrySdk.initPaymentPlugin(data);
  };

  initCardTokenizer = () => {
    const data = {
      merchantID: secrets.merchantID,
      serverURL: secrets.serverURL,
      customerEmail: 'mahmoud.ali@1trolley.com',
      customerMobile: '01115299051',
      language: FawrySdk.LANGUAGES.EN,
    };
    FawrySdk.initCardTokenizer(data);
  };

  startPaymentActivity = () => {
    FawrySdk.startPaymentActivity();
  };

  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>☆FawrySdk example☆</Text>

        <Button
          title={'Init Payment Plugin'}
          onPress={this.initPaymentPlugin}
        />

        <Button
          title={'Init Card Tokenizer'}
          onPress={this.initCardTokenizer}
        />

        <Button
          title={'start payment activity'}
          onPress={this.startPaymentActivity}
        />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'space-around',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
});
